### ISSUE TITLE
huge memory leak

### ISSUE THREAD

**Issue by evanrich** [jaroschek/home-assistant-eaton-epdu#7]
![WhatsApp Image 2024-03-29 at 20 46 34_c503139f](https://github.com/jaroschek/home-assistant-eaton-epdu/assets/518320/b7b06e1a-3145-4b6f-be1c-c8b5b5b45056)

Enabling this integration causes a huge memory leak.   I have 4GB assigned to Home assistant as a limit, and kubernetes keeps killing it.  As soon as I disable the integration, memory usage flatlines.

Monitoring 2 eaton g3 pdus, 

Plugin disabled:
![image](https://github.com/jaroschek/home-assistant-eaton-epdu/assets/518320/a5fae9af-fcdc-451c-983c-1f4951b11032)

As soon as I re-enable the plugin, add both PDU's (snmp v1 or V3, doesnt matter):
![image](https://github.com/jaroschek/home-assistant-eaton-epdu/assets/518320/87cbd917-8a41-4b15-a4d0-d4242bc3b169)

And 1 hour later:
![image](https://github.com/jaroschek/home-assistant-eaton-epdu/assets/518320/051f4fdd-d154-4477-8f8f-b24f9012387a)

it'll continue climbing until it hits 4GB, causing an OOM kill on the pod

**Comment by evanrich** [comment]
I forgot to mention, this is HASS core, running in K8s.  I copied the custom module into my custom_compoents directory, restarted homeassistant, and configured it.  running HASS: 2024.3.3

**Comment by jaroschek** [comment]
Which version do you use? Did you install the version 1.1.0 that I previously created to work with the new snmp library from HA? This version caused the massive memory leak.

I created an alternative fix for the new snmp library in version 1.0.2 and removed the other version. So you should downgrade.

The same problem occured in my other snmp related integration https://github.com/jaroschek/home-assistant-eaton-ups.

I have also 2 G3 ePDU (EMOB22) with 152 entities and I don't have a memory leak issue with version 1.0.2 installed.

**Comment by jaroschek** [comment]
I just read that you simply copied the code. I guess you just copied from the main branch? The main branch still containes the changes that caused the memory leak. Please use the code from tag 1.0.2.

**Comment by evanrich** [comment]
ahh yeah I just git cloned your main and used that, let me try 1.0.2 =)

**Comment by evanrich** [comment]
9 hours and it hasn't increased above normal.  thanks @jaroschek!
